
/**
 * generated by `gradlew genComponents`. DO NOT MODIFY
 */
package cn.jessie.stub

object JessieStubServices {
    class P0 : JessieStub.BaseService()
    class P1 : JessieStub.BaseService()
    class P2 : JessieStub.BaseService()
    class P3 : JessieStub.BaseService()
    class P4 : JessieStub.BaseService()
    class P5 : JessieStub.BaseService()
    class P6 : JessieStub.BaseService()
    class P7 : JessieStub.BaseService()
    class P8 : JessieStub.BaseService()
    class P9 : JessieStub.BaseService()
    class P10 : JessieStub.BaseService()
    class P11 : JessieStub.BaseService()
    class P12 : JessieStub.BaseService()
    class P13 : JessieStub.BaseService()
    class P14 : JessieStub.BaseService()
    class P15 : JessieStub.BaseService()
    class P16 : JessieStub.BaseService()
    class P17 : JessieStub.BaseService()
    class P18 : JessieStub.BaseService()
    class P19 : JessieStub.BaseService()
}