
/**
 * generated by `gradlew genComponents`. DO NOT MODIFY
 */
package cn.jessie.main

object JessieStubServices {
    abstract class Base : cn.jessie.app.service.JessieStubService()
    class P0 : Base()
    class P1 : Base()
    class P2 : Base()
    class P3 : Base()
    class P4 : Base()
    class P5 : Base()
    class P6 : Base()
    class P7 : Base()
    class P8 : Base()
    class P9 : Base()
    class P10 : Base()
    class P11 : Base()
    class P12 : Base()
    class P13 : Base()
    class P14 : Base()
    class P15 : Base()
    class P16 : Base()
    class P17 : Base()
    class P18 : Base()
    class P19 : Base()
}