
/**
 * generated by `gradlew genComponents`. DO NOT MODIFY
 */
package cn.jessie.main

internal object JessieStubComponents {
    const val PROCESS_COUNT = 20
    const val SERVICE_COUNT = 10
    val ACTIVITY_LAUNCH_MODE_COUNTS = intArrayOf(10, 5, 3, 4)

    fun getActivityClassName(processIndex: Int, launchMode: Int, number: Int): String {
        return "cn.jessie.main.JessieStubActivities\$P${processIndex}LM${launchMode}N$number"
    }

    fun getServiceClassName(processIndex: Int, number: Int): String {
        return "cn.jessie.main.JessieStubServices\$P$processIndex"
    }

    fun getProviderAuthority(processIndex: Int): String {
        return cn.jessie.main.MainAppContext.packageName + ".jc" + processIndex
    }

}